add export of opendss results in json format
urbanopt/urbanopt-ditto-reader pull request #29
Opened 2022-02-07 18:20 UTC by kflemin

2022-02-09 20:11 UTC, kflemin commented
@tarekelgindy are you ok with this change?  I added the JSON writer so that we can pull additional information into the URBANopt reporting more easily...

2022-02-11 18:34 UTC, vtnate approved these changes
Works with the UO cli, using the `gmt` branches Kat made in conjunction with this.

2022-03-11 06:32 UTC, tarekelgindy requested changes
Sorry i just saw this now!
On line 299, the json writer should be defined with:
json_writer = JSONWriter(output_path=os.path.join(self.dss_analysis, 'json_files'))

The other parameters don't exist for the json writer

2022-03-11 22:24 UTC, kflemin commented on urbanopt_ditto_reader/urbanopt_ditto_reader.py
> +        json_writer = JSONWriter(output_path=os.path.join(self.dss_analysis, 'json_files'), split_feeders=False, split_substations=False)
```suggestion
        json_writer = JSONWriter(output_path=os.path.join(self.dss_analysis, 'json_files'), split_feeders=False, split_substations=False)
        json_writer = JSONWriter(output_path=os.path.join(self.dss_analysis, 'json_files')
```

2022-03-11 22:24 UTC, kflemin commented on urbanopt_ditto_reader/urbanopt_ditto_reader.py
> +        json_writer = JSONWriter(output_path=os.path.join(self.dss_analysis, 'json_files'), split_feeders=False, split_substations=False)
@tarekelgindy, like this?

2022-04-12 21:02 UTC, merged